myprog: rot13lib.c main.c
	gcc -g -Wall main.c rot13lib.c -o lab3

clean:
	rm rot13lib.o lab3

test:
	@echo -n "Testcase 1: "
	@./lab3 testcases/1.d testcases/1.e
	
	@echo -n "Testcase 2: "
	@./lab3 testcases/2.d testcases/2.e
	
	@echo -n "Testcase 3: "
	@./lab3 testcases/3.d testcases/3.e
	
	@echo -n "Testcase 4: "
	@./lab3 testcases/4.d testcases/4.e
